<template>
  <div class="page-grid">
    <PageHeader
      eyebrow="Dashboard"
      title="Groups"
      description="Tag-group dashboard for daily breadth, summary metrics, and ranked movers."
    />

    <FilterBar
      title="Group Scope"
      description="Review a stored tag group with ranked movers and scanner signals."
    >
      <div class="form-inline">
        <div class="field-group">
          <label for="group-tag">Tag</label>
          <input id="group-tag" v-model="tag" placeholder="semiconductor" />
        </div>
        <div class="field-group">
          <label>&nbsp;</label>
          <button @click="loadGroup">Load group</button>
        </div>
      </div>
    </FilterBar>

    <LoadingState v-if="isLoading" message="Loading group dashboard..." />
    <ErrorState
      v-else-if="errorMessage"
      title="Group request failed"
      message="The selected group could not be loaded from the backend."
      :detail="errorMessage"
    />
    <EmptyState
      v-else-if="dashboard?.meta.is_empty"
      title="No group data"
      message="Try another tag, or run make demo-data so local group metrics and scanner outputs are available."
    />
    <template v-else-if="dashboard">
      <SummaryCardGrid :cards="dashboard.summary_cards" />

      <div class="page-section-grid">
        <DetailPanel title="Group Snapshot" description="Summary metrics for the currently selected tag.">
          <MetricGrid :metrics="groupMetrics" />
        </DetailPanel>
        <MiniBarChart
          title="Group Balance"
          description="Average return, breadth, and volume ratio for the current group."
          :points="groupChartPoints"
          empty-message="No group chart data available."
        />
      </div>

      <DetailPanel title="Group Highlights" description="High-level signals for the selected tag group.">
        <ul class="highlights">
          <li v-for="item in dashboard.highlights" :key="item">{{ item }}</li>
        </ul>
      </DetailPanel>

      <div class="page-section-grid">
        <RankedListSection v-for="list in dashboard.ranked_lists" :key="list.key" :list="list" />
        <SortableTableSection
          title="Scanner Flags"
          description="Flagged instruments generated by the group scanner."
          :columns="flagColumns"
          :rows="flagRows"
          default-sort-by="change_pct"
          default-sort-direction="desc"
          empty-message="No flagged instruments for this group."
        />
      </div>
    </template>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from "vue";

import { fetchGroupDashboard } from "@/api/dashboard";
import { normalizeApiError } from "@/api/http";
import DetailPanel from "@/components/DetailPanel.vue";
import EmptyState from "@/components/EmptyState.vue";
import ErrorState from "@/components/ErrorState.vue";
import FilterBar from "@/components/FilterBar.vue";
import LoadingState from "@/components/LoadingState.vue";
import MetricGrid from "@/components/MetricGrid.vue";
import MiniBarChart from "@/components/MiniBarChart.vue";
import PageHeader from "@/components/PageHeader.vue";
import RankedListSection from "@/components/RankedListSection.vue";
import SortableTableSection from "@/components/SortableTableSection.vue";
import SummaryCardGrid from "@/components/SummaryCardGrid.vue";
import type { GroupDashboardRead } from "@/types/dashboard";
import { formatNumber, formatPercent } from "@/utils/formatters";

const tag = ref("semiconductor");
const dashboard = ref<GroupDashboardRead | null>(null);
const isLoading = ref(false);
const errorMessage = ref<string | null>(null);

const flagColumns = [
  { key: "symbol", label: "Symbol" },
  { key: "change_pct", label: "Change %" },
  { key: "volume_ratio", label: "Volume Ratio" },
  { key: "reasons", label: "Reasons" },
];

const flagRows = computed(() =>
  dashboard.value?.data?.scanner?.flagged_instruments.map((item) => ({
    symbol: item.symbol,
    change_pct: Number(item.close_change_pct),
    volume_ratio: item.volume_ratio ? Number(item.volume_ratio) : null,
    reasons: item.reasons.join(", "),
  })) ?? [],
);

const groupMetrics = computed(() => {
  const snapshot = dashboard.value?.data;
  if (!snapshot) {
    return [];
  }
  return [
    { label: "Members", value: formatNumber(snapshot.summary.member_count), hint: "tag coverage" },
    { label: "Average Change", value: formatPercent(snapshot.summary.average_close_change_pct), hint: "daily move" },
    { label: "Above SMA", value: formatPercent(snapshot.summary.percentage_above_sma), hint: "breadth" },
    {
      label: "Scanner Flags",
      value: formatNumber(snapshot.scanner?.flagged_instruments.length ?? 0),
      hint: "signal hits",
    },
  ];
});

const groupChartPoints = computed(() => {
  const snapshot = dashboard.value?.data;
  if (!snapshot) {
    return [];
  }
  return [
    {
      label: "Avg Return",
      value: Number(snapshot.scanner?.average_daily_return_pct ?? snapshot.summary.average_close_change_pct),
      tone: "info" as const,
    },
    {
      label: "Above SMA",
      value: Number(snapshot.summary.percentage_above_sma),
      tone: "positive" as const,
    },
    {
      label: "Volume Ratio",
      value: Number(snapshot.scanner?.average_volume_ratio ?? 0),
      tone: "neutral" as const,
    },
  ];
});

async function loadGroup(): Promise<void> {
  isLoading.value = true;
  errorMessage.value = null;
  try {
    dashboard.value = await fetchGroupDashboard(tag.value);
  } catch (error) {
    errorMessage.value = normalizeApiError(error).detail;
  } finally {
    isLoading.value = false;
  }
}

onMounted(loadGroup);
</script>

<style scoped>
.highlights {
  margin: 0;
  padding-left: 1.1rem;
  display: grid;
  gap: 0.5rem;
}
</style>
